<?php
/**
 * ChargingLogResourceApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Api Documentation
 *
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ChargingLogResourceApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ChargingLogResourceApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createChargingLogUsingPOST
     *
     * createChargingLog.
     *
     */
    public function testCreateChargingLogUsingPOST()
    {
    }

    /**
     * Test case for deleteChargingLogUsingDELETE
     *
     * deleteChargingLog.
     *
     */
    public function testDeleteChargingLogUsingDELETE()
    {
    }

    /**
     * Test case for getAllChargingLogsUsingGET
     *
     * getAllChargingLogs.
     *
     */
    public function testGetAllChargingLogsUsingGET()
    {
    }

    /**
     * Test case for getChargingLogUsingGET
     *
     * getChargingLog.
     *
     */
    public function testGetChargingLogUsingGET()
    {
    }

    /**
     * Test case for refundUsingPOST
     *
     * refund.
     *
     */
    public function testRefundUsingPOST()
    {
    }

    /**
     * Test case for updateChargingLogUsingPUT
     *
     * updateChargingLog.
     *
     */
    public function testUpdateChargingLogUsingPUT()
    {
    }
}
