<?php
/**
 * MessageTemplateResourceApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Api Documentation
 *
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * MessageTemplateResourceApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MessageTemplateResourceApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createMessageTemplateUsingPOST
     *
     * createMessageTemplate.
     *
     */
    public function testCreateMessageTemplateUsingPOST()
    {
    }

    /**
     * Test case for deleteMessageTemplateUsingDELETE
     *
     * deleteMessageTemplate.
     *
     */
    public function testDeleteMessageTemplateUsingDELETE()
    {
    }

    /**
     * Test case for getAllMessageTemplatesUsingGET
     *
     * getAllMessageTemplates.
     *
     */
    public function testGetAllMessageTemplatesUsingGET()
    {
    }

    /**
     * Test case for getMessageTemplateUsingGET1
     *
     * getMessageTemplate.
     *
     */
    public function testGetMessageTemplateUsingGET1()
    {
    }

    /**
     * Test case for updateMessageTemplateUsingPUT
     *
     * updateMessageTemplate.
     *
     */
    public function testUpdateMessageTemplateUsingPUT()
    {
    }
}
